name: CI
on:
  push:
    branches: ["main"]

jobs:
  release:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "npm"

      - name: Install Dependencies
      - run: npm ci

      - name: Run unit tests
      - run: npm test:unit

      - name: Release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        # run: npx semantic-release
      - run: echo "Release placeholder"
